config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#home'
  devise_for :users

	resources :users
  resources :lessons
  resources :searches

  # For attachinary gem (file upload)
	mount Attachinary::Engine => "/attachinary"

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	belongs_to :user
	has_attachment  :file, accept: [:jpg, :png, :gif, :pdf]
	validates :file, presence: true
	validates :title, presence: true
end

app/models/search.rb
class Search < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :lessons
  has_many :searches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	# Returns if user is authorized for this view / action
  helper_method :authorized?
	def authorized?(input=nil)
	  return false unless user_signed_in?
	  return true if current_user.admin

	  if input.nil?
	  	return false
	  end

	  if input.class == Lesson
		  return input.user_id == current_user.id
		elsif input.class == User
		  return input.id == current_user.id
		end

		# If nothing else returns, default return is false
		return false
	end	

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :check_permission, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show  
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    if current_user.nil?
      @lesson.user_id = nil
      @lesson.author = 'anonymous'
    else
      @lesson.user_id = current_user.id
      @lesson.author = User.find(@lesson.user_id).name
    end

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:title, :grade, :subject, :state, :ese, :standards, :user_id, :author, :file)
    end

    def check_permission
      unless authorized?(@lesson)
        redirect_to page_path('denied')
      end
    end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :destroy]
  before_action :trim_list

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    @results = Lesson.fuzzy_search(@search.query)
    @lessons = Lesson.all
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    @search = Search.new(search_params)
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:query, :user_id)
    end

    # Deletes the first search in the list if search list gets too big
    def trim_list
      @searches = Search.all
      @searches[0].destroy if @searches.length > 1000
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    redirect_to page_path('denied') unless authorized?
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	def home
		@search = Search.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Create', new_lesson_path %></li>
  <li><%= link_to 'Profile', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Register', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'lessonDB', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><a href="/searches/new">Search</a></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "lessonDB" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "lessonDB" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- For file upload to Cloudinary -->
    <%= cloudinary_js_config %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/lessons/_advancedSearch.html.erb
<p>
  <%= search_field(:lesson, :name) %>
  <a href="/lessons" class="btn btn-success">Search</a>
  <br>
  <%= select_tag(:subject, options_for_select([
    ['Subject', 'All'],
    ['Math', 'Math'], ['Reading', 'Reading'], 
    ['Writing', 'Writing'], ['Science', 'Science']
  ])) %>
  <%= select_tag(:grade, options_for_select([
    ['Grade', 'All'],
    ['K', 'K'], ['1st', '1'], 
    ['2nd', '2'], ['3rd', '3'],
    ['4th', '4'], ['5th', '5'],
    ['6th', '6'], ['7th', '7'],
    ['8th', '8'], ['9th', '9'],
    ['10th', '10'], ['11th', '11'],
    ['12th', '12']
  ])) %>
  <%= select_tag(:state, options_for_select([
    ['State', 'All'],
    ['AL', 'AL'], ['AK', 'AK'], 
    ['AZ', 'AZ'], ['AR', 'AR'],
    ['CA', 'CA'], ['CO', 'CO'],
    ['CT', 'CT'], ['DE', 'DE'],
    ['FL', 'FL'], ['GA', 'GA'],
    ['HI', 'HI'], ['ID', 'ID'],
    ['IL', 'IL'], ['IN', 'IN'],
    ['IA', 'IA'], ['KS', 'KS'],
    ['KY', 'KY'], ['LA', 'LA'],
    ['ME', 'ME'], ['MD', 'MD'],
    ['MA', 'MA'], ['MI', 'MI'],
    ['MN', 'MN'], ['MS', 'MS'],
    ['MO', 'MO'], ['MT', 'MT'],
    ['NE', 'NE'], ['NV', 'NV'],
    ['NH', 'NH'], ['NJ', 'NJ'],
    ['NM', 'NM'], ['NY', 'NC'],
    ['ND', 'ND'], ['OH', 'OH'],
    ['OK', 'OK'], ['OR', 'OR'],
    ['PA', 'PA'], ['RI', 'RI'],
    ['SC', 'SC'], ['SD', 'SD'],
    ['TN', 'TN'], ['TX', 'TX'],
    ['UT', 'UT'], ['VT', 'VT'],
    ['VA', 'VA'], ['WA', 'WA'],
    ['WV', 'WV'], ['WI', 'WI'],
    ['WY', 'WY']
  ])) %>
  <%= check_box_tag(:ese) %>
  <%= label_tag(:ese, "ESE") %>
</p>

app/views/lessons/_form.html.erb
<br>
<%= form_for(@lesson) do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        <div class="field">
          <%= f.label :title %><br>
          <%= f.text_field :title %>
        </div>
        <div class="field">
          <%= f.label "Google Drive, Dropbox, etc" %><br>
          <%= f.text_field :hyperlink %>
        </div>
        <br>        
        <div class="field">
          <%= f.attachinary_file_field :file, :resource_type => 'auto', :raw_convert => 'aspose' %>
          <%= f.label 'Supported file types: png, jpg, gif, pdf' %>
        </div>
      </div>
      <div class="col-sm-2">
        <div class="field">
          <%= f.label :grade %><br>
          <%= f.text_field :grade %>
        </div>
        <div class="field">
          <%= f.label :subject %><br>
          <%= f.text_field :subject %>
        </div>
        <div class="field">
          <%= f.label :state %><br>
          <%= f.text_field :state %>
        </div>
      </div>
      <div class="col-sm-8">
        <div class="field">
          <%= f.label :standards %><br>
          <%= f.text_field :standards %>
        </div>
        <div class="field">
          <%= f.label :ese %><br>
          <%= f.check_box :ese %>
        </div>
      </div>      
    </div>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
  <br>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lessons</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Grade</th>
      <th>Subject</th>
      <th>State</th>
      <th>Ese</th>
      <th>Standards</th>
      <th>Author</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.title %></td>
        <td><%= lesson.grade %></td>
        <td><%= lesson.subject %></td>
        <td><%= lesson.state %></td>
        <td><%= lesson.ese %></td>
        <td><%= lesson.standards %></td>
        <td><%= lesson.author %></td>
        <td><%= link_to 'View Lesson', lesson %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form' %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<br>

<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <p>
        <strong>Title:</strong>
        <%= @lesson.title %>
      </p>

      <p>
        <strong>Author:</strong>
        <%= @lesson.author %>
      </p>

      <p>
        <strong>Document Hyperlink:</strong>
        <a href="<%= @lesson.hyperlink %>"></a>
      </p>
    </div>
    <div class="col-xs-6">
      <p>
        <strong>Grade:</strong>
        <%= @lesson.grade %>
      </p>

      <p>
        <strong>Subject:</strong>
        <%= @lesson.subject %>
      </p>

      <p>
        <strong>State:</strong>
        <%= @lesson.state %>
      </p>

      <p>
        <strong>Ese:</strong>
        <%= @lesson.ese %>
      </p>

      <p>
        <strong>Standards:</strong>
        <%= @lesson.standards %>
      </p>
    </div>
  </div>
</div>


<p>
  <%= cl_image_tag("#{@lesson.file.public_id}.jpg", :crop => :fill) unless @lesson.file.nil? %>
</p>

<% if authorized?(@lesson) %>
  <%= link_to 'Edit', edit_lesson_path(@lesson) %> |
  <%= link_to 'Destroy', @lesson, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>

<%= link_to 'Back', lessons_path %>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/pages/denied.html.erb
<br>
<h1>You are not authorized to perform that action</h1>

app/views/searches/_advancedSearch.html.erb
<p>
<h4>Advanced search features are currently not enabled</h4>
<br>

<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :query %>
    <%= f.submit "Search", :class => "btn btn-success"%>

  <br>
  <%= select_tag(:subject, options_for_select([
    ['Subject', 'All'],
    ['Math', 'Math'], ['Reading', 'Reading'], 
    ['Writing', 'Writing'], ['Science', 'Science']
  ])) %>
  <%= select_tag(:grade, options_for_select([
    ['Grade', 'All'],
    ['K', 'K'], ['1st', '1'], 
    ['2nd', '2'], ['3rd', '3'],
    ['4th', '4'], ['5th', '5'],
    ['6th', '6'], ['7th', '7'],
    ['8th', '8'], ['9th', '9'],
    ['10th', '10'], ['11th', '11'],
    ['12th', '12']
  ])) %>
  <%= select_tag(:state, options_for_select([
    ['State', 'All'],
    ['AL', 'AL'], ['AK', 'AK'], 
    ['AZ', 'AZ'], ['AR', 'AR'],
    ['CA', 'CA'], ['CO', 'CO'],
    ['CT', 'CT'], ['DE', 'DE'],
    ['FL', 'FL'], ['GA', 'GA'],
    ['HI', 'HI'], ['ID', 'ID'],
    ['IL', 'IL'], ['IN', 'IN'],
    ['IA', 'IA'], ['KS', 'KS'],
    ['KY', 'KY'], ['LA', 'LA'],
    ['ME', 'ME'], ['MD', 'MD'],
    ['MA', 'MA'], ['MI', 'MI'],
    ['MN', 'MN'], ['MS', 'MS'],
    ['MO', 'MO'], ['MT', 'MT'],
    ['NE', 'NE'], ['NV', 'NV'],
    ['NH', 'NH'], ['NJ', 'NJ'],
    ['NM', 'NM'], ['NY', 'NC'],
    ['ND', 'ND'], ['OH', 'OH'],
    ['OK', 'OK'], ['OR', 'OR'],
    ['PA', 'PA'], ['RI', 'RI'],
    ['SC', 'SC'], ['SD', 'SD'],
    ['TN', 'TN'], ['TX', 'TX'],
    ['UT', 'UT'], ['VT', 'VT'],
    ['VA', 'VA'], ['WA', 'WA'],
    ['WV', 'WV'], ['WI', 'WI'],
    ['WY', 'WY']
  ])) %>
  <%= check_box_tag(:ese) %>
  <%= label_tag(:ese, "ESE") %>
<% end %>
</p>

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :query %>
  </div>
  <div class="actions">
    <%= f.submit "Search", :class => "btn btn-success"%>
  </div>
<% end %>

app/views/searches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Searches</h1>

<table>
  <thead>
    <tr>
      <th>Query</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.query %></td>
        <td><%= search.user_id %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New Search</h1>

<%= render 'form' %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Search</h1>
<%= render 'searches/advancedSearch' %>
<br>

<% if @results.empty? %>
  <h2>No results found</h2>
  <br>
  <h1>Lesson List</h1>
  <% output = @lessons %>
<% else %>
  <h2>Search Results:</h2>
  <% output = @results %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Grade</th>
      <th>Subject</th>
      <th>State</th>
      <th>Ese</th>
      <th>Standards</th>
      <th>Author</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% output.each do |lesson| %>
      <tr>
        <td><%= lesson.title %></td>
        <td><%= lesson.grade %></td>
        <td><%= lesson.subject %></td>
        <td><%= lesson.state %></td>
        <td><%= lesson.ese %></td>
        <td><%= lesson.standards %></td>
        <td><%= lesson.author %></td>
        <td><%= link_to 'View Lesson', lesson %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Registered Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if authorized?(@user) %></p>

app/views/visitors/_form.html.erb
<p>
  <%= search_field(:lesson, :name) %>
  <a href="/lessons" class="btn btn-success">Search</a>
  <br>
  <%= select_tag(:subject, options_for_select([
    ['Subject', 'All'],
    ['Math', 'Math'], ['Reading', 'Reading'], 
    ['Writing', 'Writing'], ['Science', 'Science']
  ])) %>
  <%= select_tag(:grade, options_for_select([
    ['Grade', 'All'],
    ['K', 'K'], ['1st', '1'], 
    ['2nd', '2'], ['3rd', '3'],
    ['4th', '4'], ['5th', '5'],
    ['6th', '6'], ['7th', '7'],
    ['8th', '8'], ['9th', '9'],
    ['10th', '10'], ['11th', '11'],
    ['12th', '12']
  ])) %>
  <%= select_tag(:state, options_for_select([
    ['State', 'All'],
    ['AL', 'AL'], ['AK', 'AK'], 
    ['AZ', 'AZ'], ['AR', 'AR'],
    ['CA', 'CA'], ['CO', 'CO'],
    ['CT', 'CT'], ['DE', 'DE'],
    ['FL', 'FL'], ['GA', 'GA'],
    ['HI', 'HI'], ['ID', 'ID'],
    ['IL', 'IL'], ['IN', 'IN'],
    ['IA', 'IA'], ['KS', 'KS'],
    ['KY', 'KY'], ['LA', 'LA'],
    ['ME', 'ME'], ['MD', 'MD'],
    ['MA', 'MA'], ['MI', 'MI'],
    ['MN', 'MN'], ['MS', 'MS'],
    ['MO', 'MO'], ['MT', 'MT'],
    ['NE', 'NE'], ['NV', 'NV'],
    ['NH', 'NH'], ['NJ', 'NJ'],
    ['NM', 'NM'], ['NY', 'NC'],
    ['ND', 'ND'], ['OH', 'OH'],
    ['OK', 'OK'], ['OR', 'OR'],
    ['PA', 'PA'], ['RI', 'RI'],
    ['SC', 'SC'], ['SD', 'SD'],
    ['TN', 'TN'], ['TX', 'TX'],
    ['UT', 'UT'], ['VT', 'VT'],
    ['VA', 'VA'], ['WA', 'WA'],
    ['WV', 'WV'], ['WI', 'WI'],
    ['WY', 'WY']
  ])) %>
  <%= check_box_tag(:ese) %>
  <%= label_tag(:ese, "ESE") %>
</p>

app/views/visitors/home.html.erb
<div class="jumbotron">
  <div class="container" ID="landing-contain">
    <h1>lessonDB</h1>
    <h3>Find and share lesson plans</h3>

    <%= render 'searches/form' %>

  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-4">
      <h2>All your files, Everywhere</h2>
      <p>Download and print your lessons from any computer with internet access</p>
      <p><a class="btn btn-default" href="/users/sign_up" role="button">Sign Up &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Stand on the Shoulders of Giants</h2>
      <p>Find lessons created by other teachers</p>
      <p><a class="btn btn-default" href="/searches/new" role="button">Find lessons &raquo;</a></p>
   </div>
    <div class="col-md-4">
      <h2>Battle-tested Lessons</h2>
      <p>Community-reviewed, State and Federal standards documented</p>
      <p><a class="btn btn-default" href="#" role="button">Learn more &raquo;</a></p>
    </div>
  </div>

  <hr>

  <footer>
    <p>Site Design by Robert Anderson</p>
  </footer>
</div> <!-- /container -->

<script>
  $('li').onclick = function(){
    alert('test');
  }
</script>

app/views/visitors/index.html.erb
<!-- Bootstrap core JavaScript
================================================== -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="../../dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container" ID="landing-contain">
    <h1>lessonDB</h1>
    <h3>Find and share lesson plans</h3>

    <%= render 'searches/form' %>

  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-4">
      <h2>All your files, Everywhere</h2>
      <p>Download and print your lessons from any computer with internet access</p>
      <p><a class="btn btn-default" href="#" role="button">Sign Up &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Stand on the Shoulders of Giants</h2>
      <p>Find lessons created by other teachers</p>
      <p><a class="btn btn-default" href="#" role="button">Find lessons &raquo;</a></p>
   </div>
    <div class="col-md-4">
      <h2>Battle-tested Lessons</h2>
      <p>Community-reviewed, State and Federal standards documented</p>
      <p><a class="btn btn-default" href="#" role="button">See Standards &raquo;</a></p>
    </div>
  </div>

  <hr>

  <footer>
    <p>Site Design by Robert Anderson</p>
  </footer>
</div> <!-- /container -->

<script>
  $('li').onclick = function(){
    alert('test');
  }
</script>